package main

import (
	"flag"
	"fmt"
	"github.com/goccy/go-yaml"
	"github.com/oriser/regroup"
	"log"
	"os"
	"path/filepath"
	"photos/photos"
	"strings"
	"time"
)

const (
	scriptBegin = `
#
# THIS SCRIPT IS GENERATED BY PHOTO-ORGANIZER
# TIME: %time%
# USE CAUTIOUSLY
#
`
)

func main() {
	log.SetPrefix("# ")
	configPath := flag.String("c", "", "The config file")
	testRegex := flag.String("r", "", "Test regex")
	testString := flag.String("s", "", "Test String")
	overwrite := flag.Bool("w", false, "Overwrite target if exist")
	outputScript := flag.String("o", "", "Export operations to a script. If not provided, it will flood your terminal (or pipe)")
	needHelp := flag.Bool("h", false, "Show Help")
	acceptAll := flag.Bool("y", false, "Confirm all operations automatically.")
	checkSize := flag.Bool("check", false, "Check size from src to dst if file is exist")
	flag.Parse()
	if *needHelp {
		flag.Usage()
		return
	}
	if *testString != "" {
		if *testRegex != "" {
			test(*testRegex, *testString)
		} else {
			if *configPath == "" {
				log.Fatalf("config must be provided")
			}
			testWithConfig(*configPath, *testString)
		}
		return
	}
	if *configPath == "" {
		log.Fatalf("config must be provided")
	}
	log.Println("Loading config from ", *configPath)
	srcDir, dstDir, rules := loadConfig(*configPath)
	log.Println("Source path: ", srcDir)
	log.Println("Dst path: ", dstDir)
	log.Printf("%v rules loaded. ", len(rules))
	organizer := photos.CreateOrganizer(*checkSize, srcDir)
	organizer.Rules = rules
	info := organizer.CollectInfo()
	if !*acceptAll {
		log.Println("Photo info collected. Once you checked the logs type yes in capital")
		YES := ""
		for YES != "YES" {
			_, _ = fmt.Scanln(&YES)
		}
	}
	operations := organizer.Prepare(*overwrite, info, dstDir)
	if operations == nil {
		log.Printf("Some errr occurred while preparing. Please check logs above.")
		return
	}
	if *outputScript != "" {
		exportToScript(*overwrite, outputScript, operations)
	} else {
		fmt.Print(generateScript(*overwrite, operations))
	}

}

func generateScript(overwrite bool, operations *photos.Ops) string {
	str := strings.Builder{}
	str.WriteString(strings.ReplaceAll(scriptBegin, "%time%", time.Now().String()) + "\n")
	ops := *operations
	dirs := make(map[string]bool)
	for dst, _ := range ops {
		dirs[filepath.Dir(dst)] = true
	}
	for k, _ := range dirs {
		d := escape(k)
		str.WriteString(fmt.Sprintf("echo \"Creating directory %v\"\ntest ! -d \"%v\" && mkdir -p \"%v\"\n", d, d, d))
	}
	for dst, src := range ops {
		cmd := fmt.Sprintf(
			"echo Copying \"%v -> %v\"\ntest ! -f \"%v\" && cp \"%v\" \"%v\"\n",
			escape(src.SourceFile), escape(dst),
			escape(dst), escape(src.SourceFile), escape(filepath.Dir(dst)),
		)
		if overwrite {
			cmd = fmt.Sprintf(
				"echo Copying \"%v -> %v\"\ncp \"%v\" \"%v\"\n",
				escape(src.SourceFile), escape(dst),
				escape(src.SourceFile), escape(filepath.Dir(dst)),
			)
		}
		str.WriteString(cmd)
	}
	return str.String()
}

func exportToScript(overwrite bool, outputScript *string, operations *photos.Ops) {
	log.Println("Exporting script to ", *outputScript)
	if err := os.MkdirAll(filepath.Dir(*outputScript), 0755); err != nil {
		log.Fatalf("Cannot make directory: ", err)
	}
	file, err := os.Create(*outputScript)
	if err != nil {
		log.Fatalf("Cannot open script file: %v", err)
	}
	_, err = file.WriteString(generateScript(overwrite, operations))
	if err != nil {
		log.Fatalf("Cannot write script file: %v", err)
	}
	return
}

func escape(s string) string {
	return strings.ReplaceAll(s, "\"", "\\\"")
}

func testWithConfig(configPath string, s string) {
	log.Println("Loading rules from", configPath)
	_, _, rules := loadConfig(configPath)
	log.Printf("%v rules loaded", len(rules))
	for i := range rules {
		log.Println("Testing rule ", i)
		g, e := rules[i].Groups(s)
		if e != nil {
			log.Printf("Cannot match with rule %v: %v", i, e)
			continue
		}
		for k, v := range g {
			log.Printf("%v : %v", k, v)
		}
	}
}

func test(s string, s2 string) {
	re := regroup.MustCompile(s)
	g, e := re.Groups(s2)
	if e != nil {
		log.Fatalf("Match error: %v", e)
	}
	for k, v := range g {
		log.Printf("%v : %v", k, v)
	}
}

type AppConfig struct {
	RootDir  string   `yaml:"src"`
	DstDir   string   `yaml:"dst"`
	Patterns []string `yaml:"patterns"`
}

func loadConfig(path string) (rootDir string, dstDir string, _rules []*regroup.ReGroup) {
	file, err := os.Open(path)
	if err != nil {
		log.Fatalf("Cannot load config %v", err)
	}
	defer file.Close()
	decoder := yaml.NewDecoder(file)
	config := &AppConfig{}
	if erro := decoder.Decode(config); erro != nil {
		log.Fatalf("Failed to parse config file: %v", err)
	}
	rules := make([]*regroup.ReGroup, 0)
	for _, pattern := range config.Patterns {
		rules = append(rules, regroup.MustCompile(pattern))
	}
	return config.RootDir, config.DstDir, rules
}
